name: Dev Install Test
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  Dev-Install-Test:
    name: Dev Install & Test on Node ${{ matrix.node }} [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # gh macos runnners does not come with docker, could not get it installed
        # see: https://github.community/t/is-it-possible-to-install-and-configure-docker-on-macos-runner/16981/3
        # windows runner does not suppport linux containers
        # see:
        os: [ubuntu-latest] #, windows-latest] #,macos-latest]
        node: [14, 16]
    steps:
      # - name: Install Docker (Macos)
      #   if: ${{ matrix.os == 'macos-latest'}}
      #   run: |
      #     brew install docker-machine docker
      #     docker-machine create default
      #     docker-machine env default
      #     eval "$(docker-machine env default)"
      #     docker ps

      - name: Checkout ab-cli
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install npm packages
        run: npm i

      - name: Initialize docker swarm
        run: docker swarm init --advertise-addr 127.0.0.1

      - name: Install AppBuilder
        run: npm run ci:dev-install

      - name: Setup Test Stack
        working-directory: ./ab-test
        run: node ../index.js test setup ab

      - name: Launch Test Stack
        working-directory: ./ab-test
        run: node ../index.js test waitBoot ab

      - name: Test the Test Stack (Cypress)
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./ab-test
          project: ./test/e2e
          # TEMP: Skip failing test
          spec: |
            ./test/e2e/cypress/integration/0001_portal_auth_login.js
            ./test/e2e/cypress/integration/0002_portal_work.js

      - name: Take Down Test Stack
        run: node ../index.js test down ab
        working-directory: ./ab-test

      - name: Launch Main Stack
        run: ./UP.sh -t -q
        working-directory: ./ab-test

      - name: Test Main Stack (Cypress)
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./ab-test
          project: ./test/e2e
          config: baseUrl=http://localhost:80
          wait-on: "http://localhost:80"
          wait-on-timeout: 300
          env: stack=ab
          # TEMP: Skip failing test
          spec: |
            ./test/e2e/cypress/integration/0001_portal_auth_login.js
            ./test/e2e/cypress/integration/0002_portal_work.js

      - name: Take Down Main Stack
        run: ./Down.sh
        working-directory: ./ab-test
